import matplotlib
import matplotlib.pylab as plt
import matplotlib.patches

def plot_true_alt(p,q):
    RTC = matplotlib.patches.Rectangle((0.,.6),1-p,.1,facecolor='blue')
    RTO = matplotlib.patches.Rectangle((1-p,.6),p,.1,facecolor="orange")
    RAC = matplotlib.patches.Rectangle((0.,.2),1-q,.1,facecolor="blue")
    RAO = matplotlib.patches.Rectangle((1-q,.2),q,.1,facecolor="orange")
    Ax = plt.gca()
    Ax.add_patch(RTC)
    Ax.add_patch(RTO)
    Ax.add_patch(RAC)
    Ax.add_patch(RAO)
    Ax.yaxis.set_major_locator(plt.NullLocator())
    plt.xlabel("Probability")
    Ax.text(.05,.725, "True Model: p="+str(p),fontsize=18)
    Ax.text(.05,.325, "Alternate Model: p="+str(q),fontsize=18)
    matplotlib.rcParams.update({'font.size':18})


def plot_true_alt2(p,q):
    RT0 = matplotlib.patches.Rectangle((0.,.6),(1-p)**2,.1,facecolor='blue')
    RT1 = matplotlib.patches.Rectangle(((1-p)**2,.6),2*p*(1-p),.1,facecolor="green")
    RT2 = matplotlib.patches.Rectangle(((1-p)**2+2*p*(1-p),.6),p**2,.1,facecolor='orange')
    RA0 = matplotlib.patches.Rectangle((0.,.2),(1-q)**2,.1,facecolor='blue')
    RA1 = matplotlib.patches.Rectangle(((1-q)**2,.2),2*q*(1-q),.1,facecolor="green")
    RA2 = matplotlib.patches.Rectangle(((1-q)**2+2*q*(1-q),.2),q**2,.1,facecolor='orange')
    Ax = plt.gca()
    Ax.add_patch(RT0)
    Ax.add_patch(RT1)
    Ax.add_patch(RT2)
    Ax.add_patch(RA0)
    Ax.add_patch(RA1)
    Ax.add_patch(RA2)
    Ax.yaxis.set_major_locator(plt.NullLocator())
    plt.xlabel("Probability")
    Ax.text(.05,.725, "True Model (2 Reps): p="+str(p),fontsize=18)
    Ax.text(.05,.325, "Alternate Model (2 Reps): p="+str(q),fontsize=18)
    matplotlib.rcParams.update({'font.size':18})


def plot_nchannels(p):
    RA0 = matplotlib.patches.Rectangle((0.,.6),(1-p),.1,facecolor='blue')
    RA1 = matplotlib.patches.Rectangle(((1-p),.6),p,.1,facecolor="green")
    RT0 = matplotlib.patches.Rectangle((0.,.2),(1-p)**2,.1,facecolor='blue')
    RT1 = matplotlib.patches.Rectangle(((1-p)**2,.2),2*p*(1-p),.1,facecolor="green")
    RT2 = matplotlib.patches.Rectangle(((1-p)**2+2*p*(1-p),.2),p**2,.1,facecolor='orange')
    Ax = plt.gca()
    Ax.add_patch(RT0)
    Ax.add_patch(RT1)
    Ax.add_patch(RT2)
    Ax.add_patch(RA0)
    Ax.add_patch(RA1)
    Ax.yaxis.set_major_locator(plt.NullLocator())
    plt.xlabel("Probability")
    Ax.text(.05,.725, "One Channel: p="+str(p),fontsize=18)
    Ax.text(.05,.325, "Two Channels: p="+str(p),fontsize=18)
    matplotlib.rcParams.update({'font.size':18})

plt.figure(1)
plot_true_alt(.9,.8)
plt.figure(2)
plot_true_alt(.8,.9)
plt.figure(3)
plot_true_alt2(.8,.9)
plt.figure(4)
plot_nchannels(.8)
plt.show()